### ISSUE TITLE
Support compose

### ISSUE THREAD

**Issue by fjr619** [khushpanchal/Ketch#1]
Please make it to support jetpack compose

**Comment by khushpanchal** [comment]
> Please make it to support jetpack compose

You can use it with compose as well. There is no limitation. Just create the instance, call the download function and pass the url. You can create the instance in Viewmodel as well if you want to retain the instance while configuration changes.

**Comment by PrimoDev23** [comment]
While it might be possible to have this logic in the ViewModel, you should rather create an abstraction in your domain layer and inject it into your ViewModel. This is much more best practice. Doesn't change the fact it works the same way for Compose 😄

**Comment by khushpanchal** [comment]
True @PrimoDev23 🙌

**Comment by khushpanchal** [comment]
Closing the issue
