### ISSUE TITLE
How to automatically delete the download when finished from recyclerview?

### ISSUE THREAD

**Issue by hamza0786** [khushpanchal/Ketch#11]
Hi!
How to automatically delete the download when finished from recyclerview?

**Comment by khushpanchal** [comment]
To automatically delete the downloaded file from the RecyclerView, you can observe the Flow of DownloadModel list and check the status field. When the status is SUCCESS, you can remove the item from the RecyclerView adapter.

Something like this:
```
downloadModelList.collect { list ->
    val filteredList = list.filter { it.status != Status.SUCCESS }
    adapter.setItems(filteredList)
}
```

**Comment by hamza0786** [comment]
![Screenshot (10)](https://github.com/user-attachments/assets/f45d38ba-ca7e-4e32-b182-de7b1d13dabc)

i am getting this when i paste your code in observe method.

**Comment by hamza0786** [comment]
and remember i only want to delete the downloaded item view from recyclerview not the download file itself from the storage.

**Comment by khushpanchal** [comment]
Not like this, that was for reference, do like this

```
ketch.observeDownloads().collect { list -> val filteredList = list.filter { it.status != Status.SUCCESS } adapter.submitList(filteredList) }
```

**Comment by hamza0786** [comment]
Thank you very much for helping me out brother!
