### ISSUE TITLE
How to start the download automatically.

### ISSUE THREAD

**Issue by hamza0786** [khushpanchal/Ketch#12]
Hi Brother!

how can i start the download automatically without going to the mainfragment by passing the download url through Bundle arguments.

like this for example:

https://github.com/user-attachments/assets/e1b63a4c-24d5-478a-a84f-7850a28d49e9

**Comment by khushpanchal** [comment]
You can download from anywhere it may not necessarily be MainFragment or any screen. Ketch is a singleton class, you can inject it in any of your class as per your use case and call download function. For observing, you can observe it in any scope, just call observeDownloads function. In case you do not want to inject the class externally just call like this from any class.

```
Ketch.builder().build(context).download(url, fileName, path)

CoroutineScope(Dispatchers.IO).launch {
    ketch.observeDownloads().collect{ list->}
}
```
Make sure to cancel the scope at appropriate place to avoid unnecessary observing

**Comment by hamza0786** [comment]
Hi its working but asa i close the app or put app in background the download stopped progressing and then it Failed any solution? of this will be appericiated!

**Comment by hamza0786** [comment]
no need i figured it out.
thanks for reaching me out!
