### ISSUE TITLE
Download Failed issue with fileNames

### ISSUE THREAD

**Issue by hamza0786** [khushpanchal/Ketch#13]
Hi!
the download failed when the fileName is these:

"A Personal Story From The Secret Service Exposes The Agency (Ep 2300) - 08/02/2024"
"Jacques - "Absolve""

but works fine when fileName is:
"Frog 4k HDR 10+ Dolby vision"

can you help in fixing this issue.

as i think the issue is seems to be that the library does not supporting the filenames with some special character and spaces etc.

**Comment by khushpanchal** [comment]
File name you are sending is invalid, avoid adding special character in fileName.

You can validate filename before sending to library like this:
```
 fileName.replace("[^a-zA-Z0-9-. ]+".toRegex(), "_")

```

**Comment by hamza0786** [comment]
thanks!
