### ISSUE TITLE
timeout problems

### ISSUE THREAD

**Issue by Wizardeirr** [khushpanchal/Ketch#18]
When my internet is down all download is going to failure and when internet comes thats not resume. You said i had fixed that. can u help me ?

**Comment by khushpanchal** [comment]
In case of no internet download will be failed, client need to call retry function in that case.

You can have a connectivity listener and can retry download in case of failure.

**Comment by Wizardeirr** [comment]
it will cause data useless, for example i will download anything. 200 Mb, i did download 195 m/bs and internet shutdown. User will download retry. Think about that for each device we need to keep 195 mbs and when internet is come we should resume to download

**Comment by khushpanchal** [comment]
Data will not loss. Younwill call retry(id) function and download will resume from where it failed.

Suppose user download 200 mb video and download fails after 195 mb, due to any reason, when you call retry function it will resume from 195 mb only.
