### ISSUE TITLE
How to clear Ketch database only, without deleting file? 

### ISSUE THREAD

**Issue by hemantp66** [khushpanchal/Ketch#21]
As my download is finished from ketch , i am observing and saving entry in my apps database, now there is no need to keep additinal entry in ketch database, so i want to ckear that entry?

**Comment by khushpanchal** [comment]
Currently there is no functionality to delete only entry and not file.
Why you need to clear the entry of the downloaded video anyway?

Anyways I am planning to add one additional Boolean in clearDb function in case someone want to only delete the entry. Feel free to create the PR if you want to implement it.

**Comment by khushpanchal** [comment]
@hemantp66 this is done in version 2.0.2

To clear only db entry, use `clearDb(id, false)` function, this will clear only DB entry and skip file deletion
