### ISSUE TITLE
WORKER FAILED in release mode

### ISSUE THREAD

**Issue by triandamai** [khushpanchal/Ketch#25]
I dont know why, but when my aplication running on release mode, the download worker from ketch show WORKER FAILURE.
am i missing something?

<img width="1119" alt="Screenshot 2024-08-29 at 11 31 18" src="https://github.com/user-attachments/assets/c2ea5d35-52e2-413e-8cc9-df44e1a90db1">

**Comment by KhunHtetzNaing** [comment]
Ketch uses [Retrofit](https://github.com/square/retrofit) to download files. If you have `isMinifyEnabled` enabled, you'll need to add ProGuard [rules](https://github.com/square/retrofit?tab=readme-ov-file#r8--proguard).

**Comment by phucynwa** [comment]
> Ketch uses [Retrofit](https://github.com/square/retrofit) to download files. If you have `isMinifyEnabled` enabled, you'll need to add ProGuard [rules](https://github.com/square/retrofit?tab=readme-ov-file#r8--proguard).

@khushpanchal Please add this ProGuard rules to README for new users.
