### ISSUE TITLE
Question: HTTP engine question

### ISSUE THREAD

**Issue by emartynov** [khushpanchal/Ketch#27]
I noticed that library uses retrofit. The next questions/suggestions:
1. Many libraries that utilise okhttp allow users to pass okhttp configured for app needs. I see that this lib has configuration to modify requests but maybe you can check how coil is doing it (https://coil-kt.github.io/coil/recipes/#using-a-custom-okhttpclient).
2. Maybe ditch Retrofit and just use okhttp for smaller transitive dependencies?

**Comment by khushpanchal** [comment]
@emartynov thanks for the suggestion, I have added option to pass custom okhttp client from outside while initializing the library.
Please check version 2.0.2
