### ISSUE TITLE
Support for appendable download and file uploading

### ISSUE THREAD

**Issue by Dmitriy1892** [khushpanchal/Ketch#4]
Hi, thank you for your library!

It will be nice to provide a way for appendable (chunked) files downloading (for example, using AWS S3 protocol) with schedule/pause/resume functionality. The specific of that way is a multiple network calls for downloading every chunk and saving it to file part by part.

Also, it will be nice to having a possibility to upload file from device to server or cloud storage.

What do you mean about this?

**Comment by khushpanchal** [comment]
Yes I have planned it for future release.

**Comment by khushpanchal** [comment]
@Dmitriy1892 please checkout the version 2.0.0 https://github.com/khushpanchal/Ketch
Added the functionality mentioned
