### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by Wizardeirr** [khushpanchal/Ketch#6]
Ty for this library its very usefull i think. especially should be Pause and resume states. 
My issue ; 
My internet is going sometimes and my download progress is stopping a few seconds later my internet is coming but my download progress is not going to pause or timeout. Directly going to error. And all download state is lost. 
How can i resolve this problem are you checking this situation on library?

**Comment by khushpanchal** [comment]
Hi @Wizardeirr I will be soon adding the functionality of handling retry-failure, pause-resume.

**Comment by khushpanchal** [comment]
@Wizardeirr please check out the Version 2.0.0 https://github.com/khushpanchal/Ketch
Added the functionalities mentioned.
